# 'study_prefix' should be a string at the start of each table. We'll use this
# to clean up queries, so it should be unique. Name your tables in the following
# format: [study_prefix]__[table_name]. It should probably, but not necessarily,
# be the same name as the folder the study definition is in.
study_prefix = "template"


# The following section describes all tables that should be generated directly
# from SQL files.

# 'stages' is a dictionary into which we can put different groups of related
# tables we want to build. We can have more than one stage if that makes sense
# for the study in question. We'll create a single stage, default (and if we
# didn't create this, a stage named 'default' would be automatically configured
# matching the first stage in this file)

# note the double bracket syntax, which means 'we are adding an action to an array
# at the key named 'default' in the dictionary named 'stages'
[[stages.default]]
# 'type' defines how the library reads the action. There are seven valid types:
# - 'build:parallel' will run sql generating artifacts simultaneously, which
#   assumes there are no dependencies between files
# - 'build:serial' will run sql generating artifacts in sequence, which is slower
#   but allows one query to depend on the previous.
# - 'export:counts' will export tables, marking them as count tables
# - 'export:annotated_counts' will export tables, marking them as annotated count tables
# - 'export:flat' will export tables, marking them as flat statistics tables
# - 'export:meta' will export tables, marking them as metadata tables
# - 'submanifest' indicates that a file is a submanifest, containing a combination
#   of build/export actions
# stages of a type other than submanifest will only run during the associated library
# action, and will otherwise be ignored.
type = "build:parallel"
# the description will be displayed when the study is in the process of being
# build in the CLI
description = "external data"
# for actions beginning with 'build:', we look for a key named 'files', which
# contains a list the following kinds of study artifacts in any combination:
#   - Raw SQL queries, ending in '.sql'
#   - Python builders, subclassing the library's BaseTableBuilder, ending in '.py'
#   - Workflow configs, ending in '.toml' or '.workflow'
# For more information about these, see the documentation:
# https://docs.smarthealthit.org/cumulus/library/
files = [
    "workflows/upload_encounter_class.workflow"    
]

[[stages.default]]
type = "build:parallel"
description = "study cohort"
files = [
  "queries/patients.sql",
]

[[stages.default]]
type = "build:serial"
description = "other resources for patients"
files=[
    "builders/conditions.py",
    "queries/encounters.sql",
]

[[stages.default]]
type = "build:parallel"
description = "study metadata"
files= [
    "queries/meta_date.sql",
    "queries/meta_version.sql",
]

[[stages.default]]
type = "build:parallel"
description = "metadata_tables"
files = ["workflows/counts.workflow"]

# Now we'll add some export actions to the default stage, with specific types that
# determine how the export is handled.

# The following tables will be exported and labeled as aggregate count tables.
# In most cases, tables should go in this list.
[[stages.default]]
description = "condition count tables"
type = "export:counts"
tables = [
    "template__count_condition",
]

# In some cases, you may want to annotate count data with metadata from another
# source. Most commonly, this is used to add data related to a code (like its
# display value or code system) from another source.

[[stages.default]]
description = "annotated encounter count tables"
type = "export:annotated_counts"
tables = [
    "template__count_encounter_annotated",
]

# Some specific tables (like those produced by data metrics) are a special type
# of tables, that are flat summary statistics tables. 

# [[stages.default]]
# description = "flat statistics tables"
# type = "export:flat"
# tables = [
#     "template__q_influenza",
# ]

# Tables that shouldn't go through aggregation, but instead contain data about
# the export itself, should be marked as metadata. Two types are expected as of this
# writing: a `meta_date` table, outlining the period over which the study extends,
# and a `meta_version` table, which should be incremented whenever the format of
# your export tables changes. See the core study for examples of how to structure
# these tables.

[[stages.default]]
description = "metadata tables"
type = "export:meta"
tables = [
  "template__meta_date",
  "template__meta_version",
]

# The following section is for advanced/unusual study use cases

# [advanced_options]

# If you want to override the default schema name to an explicit one, you can define
# the name of this schema here. 99% of the time, this is not the behavior you want -
# you want library data to be in the same schema as your data source, since this allows
# you to keep track of where your source data for a given study run came from.
#
# The intended use case for this is for static/slow moving data sets that are external
# to your EHR data - this is typically things like coding systems.
#
# These should be read only use cases - if you want to do additional iterations with
# the contents of one of these reference sets, do it in the study, not in the reference
# itself.

# use_dedicated_schema="alternate_schema_name"

